name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'green'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'Github token, needed to read PR descriptions'
    required: true
  related_issue:
    description: 'Check if PR has a related issue'
    default: 'true'
  jira_ticket:
    description: 'Check if a related Jira Ticket has been mentioned'
    default: 'false'
  jira_project:
    description:
      'What project the issue is in within Jira, only applies if jira_ticket is
      true'
    default: 'Example'
  jira_url:
    description: 'URL to jira instance, only supporting public servers for now'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
