name: 'pr-requirements'
description:
  'Provides a status check on GitHub issue references and JIRA tickets'
author: 'redhat-performance'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-pull-request'
  color: 'green'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'Github token, needed to read PR descriptions'
    required: true
  related_issue:
    description: 'Check if PR has a related issue'
    default: 'true'
  jira_ticket:
    description: 'Check if a related Jira Ticket has been mentioned'
    default: 'false'
  jira_project:
    description:
      'What project the issue is in within Jira, only applies if jira_ticket is
      true'
    default: 'Example'
  jira_url:
    description: 'URL to jira instance, only supporting public servers for now'

runs:
  using: node20
  main: dist/index.js
